"""Central catalog of developer tools."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable


@dataclass(frozen=True)
class Tool:
    slug: str
    name: str
    description: str
    category: str
    icon: str
    actions: tuple[str, ...] = ()
    template: str = 'toolbox/tool_generic.html'
    dual_input: bool = False
    dual_labels: tuple[str, str] = ('输入 A', '输入 B')
    placeholder: str = ''
    placeholder_b: str = ''
    options: tuple[dict, ...] = ()
    tags: tuple[str, ...] = ()


CATEGORIES = [
    ('json', 'JSON / 数据'),
    ('encode', '编码加密'),
    ('convert', '转换工具'),
    ('text', '文本代码'),
    ('generate', '生成工具'),
    ('network', '网络运维'),
    ('reference', '速查参考'),
]


TOOLS: list[Tool] = [
    # JSON / Data
    Tool(
        slug='json-format',
        name='JSON 格式化',
        description='校验、美化、压缩 JSON，支持 Unicode 转义与排序键。',
        category='json',
        icon='{}',
        actions=('format', 'minify', 'validate', 'sort'),
        placeholder='{"name":"StackBox","ok":true}',
        tags=('json', '格式化', '校验'),
    ),
    Tool(
        slug='json-yaml',
        name='JSON ↔ YAML',
        description='JSON 与 YAML 双向转换，适合配置文件与 DevOps。',
        category='json',
        icon='Y',
        actions=('to_yaml', 'to_json'),
        placeholder='{"env":"prod","replicas":3}',
        tags=('yaml', '配置'),
    ),
    Tool(
        slug='json-xml',
        name='JSON ↔ XML',
        description='JSON 与 XML 互相转换。',
        category='json',
        icon='X',
        actions=('to_xml', 'to_json'),
        placeholder='{"user":{"id":1,"name":"Ada"}}',
        tags=('xml',),
    ),
    Tool(
        slug='json-csv',
        name='JSON ↔ CSV',
        description='对象数组与 CSV 表格互转。',
        category='json',
        icon='C',
        actions=('to_csv', 'to_json'),
        placeholder='[{"id":1,"name":"Ada"},{"id":2,"name":"Grace"}]',
        tags=('csv', '表格'),
    ),
    Tool(
        slug='json-query',
        name='JSON ↔ QueryString',
        description='JSON 对象与 URL 查询参数互转。',
        category='json',
        icon='?',
        actions=('to_query', 'to_json'),
        placeholder='{"page":1,"q":"django"}',
        tags=('get', 'query'),
    ),
    Tool(
        slug='json-codegen',
        name='JSON 转代码',
        description='从 JSON 生成 Python / Go / TypeScript / Java / C# 类型定义。',
        category='json',
        icon='</>',
        actions=('python', 'go', 'typescript', 'java', 'csharp'),
        placeholder='{"id":1,"name":"Ada","tags":["dev"],"active":true}',
        options=(
            {'key': 'root_name', 'label': '根类型名', 'default': 'Root', 'type': 'text'},
        ),
        tags=('代码生成', '实体类'),
    ),
    Tool(
        slug='json-diff',
        name='JSON / 文本 Diff',
        description='对比两段文本或 JSON 的差异。',
        category='json',
        icon='±',
        actions=('diff',),
        dual_input=True,
        dual_labels=('左侧原文', '右侧对比'),
        placeholder='{"a":1,"b":2}',
        placeholder_b='{"a":1,"b":3,"c":4}',
        tags=('diff', '对比'),
    ),
    Tool(
        slug='toml-json',
        name='TOML ↔ JSON',
        description='TOML 与 JSON 互转（基于简易解析，适合常见配置）。',
        category='json',
        icon='T',
        actions=('to_json', 'to_toml'),
        placeholder='title = "StackBox"\n[server]\nport = 8000',
        tags=('toml',),
    ),
    Tool(
        slug='json-sql',
        name='JSON → SQL INSERT',
        description='把对象数组转成 SQL INSERT 语句。',
        category='json',
        icon='SQL',
        actions=('insert',),
        placeholder='[{"id":1,"name":"Ada"},{"id":2,"name":"Grace"}]',
        options=(
            {'key': 'table', 'label': '表名', 'default': 'users', 'type': 'text'},
        ),
        tags=('sql', 'insert'),
    ),
    Tool(
        slug='xml-format',
        name='XML 格式化',
        description='美化或压缩 XML。',
        category='json',
        icon='XML',
        actions=('format', 'minify'),
        placeholder='<root><user id="1"><name>Ada</name></user></root>',
        tags=('xml', '格式化'),
    ),
    Tool(
        slug='json-path',
        name='JSONPath 查询',
        description='用 JSONPath 表达式从 JSON 中提取数据。',
        category='json',
        icon='JP',
        actions=('query',),
        dual_input=True,
        dual_labels=('JSON', 'JSONPath'),
        placeholder='{"users":[{"name":"Ada"},{"name":"Grace"}]}',
        placeholder_b='$.users[*].name',
        options=(
            {'key': 'path', 'label': 'JSONPath（可空，用右侧）', 'default': '', 'type': 'text'},
        ),
        tags=('jsonpath', '查询'),
    ),
    Tool(
        slug='json-schema',
        name='JSON Schema 生成',
        description='根据示例 JSON 推断生成 JSON Schema。',
        category='json',
        icon='JS',
        actions=('generate',),
        placeholder='{"id":1,"name":"Ada","active":true}',
        tags=('schema',),
    ),
    Tool(
        slug='yaml-format',
        name='YAML 格式化',
        description='校验并美化 YAML。',
        category='json',
        icon='Y',
        actions=('format', 'validate'),
        placeholder='app:\n  name: StackBox\n  port: 8000\n',
        tags=('yaml',),
    ),
    Tool(
        slug='properties-json',
        name='Properties ↔ JSON',
        description='Java .properties 与 JSON 互转。',
        category='json',
        icon='P',
        actions=('to_json', 'to_properties'),
        placeholder='app.name=StackBox\napp.port=8000',
        tags=('properties', 'java'),
    ),

    # Encode / Crypto
    Tool(
        slug='base64',
        name='Base64 编解码',
        description='文本 Base64 编码与解码，支持 URL-safe 变体。',
        category='encode',
        icon='64',
        actions=('encode', 'decode', 'url_encode', 'url_decode'),
        placeholder='Hello, StackBox!',
        tags=('base64',),
    ),
    Tool(
        slug='url-codec',
        name='URL 编解码',
        description='URL / 百分号编码与解码。',
        category='encode',
        icon='%',
        actions=('encode', 'decode', 'encode_component', 'decode_component'),
        placeholder='https://example.com/搜索?q=django tools',
        tags=('url', '编码'),
    ),
    Tool(
        slug='html-entities',
        name='HTML 实体编解码',
        description='HTML 特殊字符实体编码与解码。',
        category='encode',
        icon='&',
        actions=('encode', 'decode'),
        placeholder='<div class="box">Hello & "world"</div>',
        tags=('html', '实体'),
    ),
    Tool(
        slug='unicode',
        name='Unicode 中文互转',
        description='中文与 \\uXXXX Unicode 转义互转。',
        category='encode',
        icon='U',
        actions=('to_unicode', 'to_chinese', 'escape', 'unescape'),
        placeholder='你好，世界',
        tags=('unicode', '中文'),
    ),
    Tool(
        slug='hex',
        name='Hex 编解码',
        description='文本与十六进制互转。',
        category='encode',
        icon='0x',
        actions=('encode', 'decode'),
        placeholder='StackBox',
        tags=('hex', '十六进制'),
    ),
    Tool(
        slug='hash',
        name='哈希生成',
        description='MD5 / SHA1 / SHA256 / SHA384 / SHA512 摘要。',
        category='encode',
        icon='#',
        actions=('hash',),
        placeholder='password123',
        options=(
            {
                'key': 'algo',
                'label': '算法',
                'type': 'select',
                'default': 'all',
                'choices': [
                    ('all', '全部'),
                    ('md5', 'MD5'),
                    ('sha1', 'SHA1'),
                    ('sha256', 'SHA256'),
                    ('sha384', 'SHA384'),
                    ('sha512', 'SHA512'),
                ],
            },
        ),
        tags=('md5', 'sha', '摘要'),
    ),
    Tool(
        slug='jwt',
        name='JWT 解码',
        description='解析 JWT Header / Payload（不验签，仅查看）。',
        category='encode',
        icon='JWT',
        actions=('decode',),
        placeholder='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c',
        tags=('jwt', 'token'),
    ),
    Tool(
        slug='password-hash',
        name='密码哈希 (bcrypt 风格说明)',
        description='生成 PBKDF2 / SHA 加盐哈希（演示用途）。',
        category='encode',
        icon='*',
        actions=('pbkdf2', 'sha256_salt'),
        placeholder='my-secret-password',
        tags=('password', 'salt'),
    ),
    Tool(
        slug='hmac',
        name='HMAC 签名',
        description='HMAC-MD5/SHA 系列消息认证码。',
        category='encode',
        icon='HM',
        actions=('sign',),
        placeholder='message to sign',
        options=(
            {'key': 'key', 'label': '密钥', 'default': 'secret', 'type': 'text'},
            {
                'key': 'algo',
                'label': '算法',
                'type': 'select',
                'default': 'sha256',
                'choices': [
                    ('md5', 'MD5'),
                    ('sha1', 'SHA1'),
                    ('sha256', 'SHA256'),
                    ('sha384', 'SHA384'),
                    ('sha512', 'SHA512'),
                ],
            },
        ),
        tags=('hmac', '签名'),
    ),
    Tool(
        slug='aes',
        name='AES / Fernet 加解密',
        description='Fernet 或 AES-GCM 对称加解密（演示用途，请自管密钥）。',
        category='encode',
        icon='AES',
        actions=('encrypt', 'decrypt'),
        placeholder='hello secret',
        options=(
            {'key': 'key', 'label': '密钥/口令', 'default': 'stackbox-demo-key', 'type': 'text'},
            {
                'key': 'mode',
                'label': '模式',
                'type': 'select',
                'default': 'fernet',
                'choices': [('fernet', 'Fernet'), ('gcm', 'AES-GCM')],
            },
        ),
        tags=('aes', '加密'),
    ),
    Tool(
        slug='jwt-sign',
        name='JWT 签发',
        description='用密钥签发 HS* JWT（演示用途）。',
        category='encode',
        icon='JWT',
        actions=('sign',),
        placeholder='{"sub":"123","name":"Ada"}',
        options=(
            {'key': 'key', 'label': '密钥', 'default': 'secret', 'type': 'text'},
            {
                'key': 'alg',
                'label': '算法',
                'type': 'select',
                'default': 'HS256',
                'choices': [('HS256', 'HS256'), ('HS384', 'HS384'), ('HS512', 'HS512')],
            },
        ),
        tags=('jwt', '签发'),
    ),
    Tool(
        slug='jwt-verify',
        name='JWT 验签',
        description='使用密钥校验 JWT 签名并解析 payload。',
        category='encode',
        icon='JWT',
        actions=('verify',),
        placeholder='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjMifQ.signature',
        options=(
            {'key': 'key', 'label': '密钥', 'default': 'secret', 'type': 'text'},
            {
                'key': 'alg',
                'label': '算法',
                'type': 'select',
                'default': 'HS256',
                'choices': [('HS256', 'HS256'), ('HS384', 'HS384'), ('HS512', 'HS512')],
            },
        ),
        tags=('jwt', '验签'),
    ),
    Tool(
        slug='rsa',
        name='RSA 密钥/加解密',
        description='生成 RSA 密钥对，或用 PEM 公钥/私钥做 OAEP 加解密。',
        category='encode',
        icon='RSA',
        actions=('keygen', 'encrypt', 'decrypt'),
        placeholder='hello rsa',
        options=(
            {'key': 'key', 'label': 'PEM 公钥/私钥', 'default': '', 'type': 'text'},
            {
                'key': 'bits',
                'label': '密钥位数',
                'type': 'select',
                'default': '2048',
                'choices': [('2048', '2048'), ('3072', '3072'), ('4096', '4096')],
            },
        ),
        tags=('rsa', '密钥'),
    ),
    Tool(
        slug='unicode-normalize',
        name='Unicode 正规化',
        description='NFC / NFD / NFKC / NFKD 正规化。',
        category='encode',
        icon='NF',
        actions=('nfc', 'nfd', 'nfkc', 'nfkd'),
        placeholder='café',
        tags=('unicode', 'normalize'),
    ),
    Tool(
        slug='base32',
        name='Base32 编解码',
        description='Base32 编码与解码。',
        category='encode',
        icon='32',
        actions=('encode', 'decode'),
        placeholder='Hello StackBox',
        tags=('base32',),
    ),
    Tool(
        slug='morse',
        name='摩斯密码',
        description='文本与摩斯电码互转。',
        category='encode',
        icon='···',
        actions=('encode', 'decode'),
        placeholder='SOS HELP',
        tags=('morse', '摩斯'),
    ),
    Tool(
        slug='rot13',
        name='ROT13 / Caesar',
        description='ROT13 与凯撒移位加密。',
        category='encode',
        icon='R13',
        actions=('rot13', 'caesar', 'decode'),
        placeholder='Hello StackBox',
        options=(
            {'key': 'shift', 'label': '移位（Caesar）', 'default': '13', 'type': 'text'},
        ),
        tags=('rot13', 'caesar'),
    ),
    Tool(
        slug='crc32',
        name='CRC32',
        description='计算文本 CRC32 校验值。',
        category='encode',
        icon='CRC',
        actions=('hash',),
        placeholder='StackBox',
        tags=('crc32', '校验'),
    ),
    Tool(
        slug='binary-text',
        name='二进制文本互转',
        description='UTF-8 文本与二进制比特串互转。',
        category='encode',
        icon='01',
        actions=('encode', 'decode'),
        placeholder='Hi',
        tags=('binary', '二进制'),
    ),
    Tool(
        slug='gzip',
        name='Gzip 压缩',
        description='Gzip 压缩/解压，结果以 Base64 表示。',
        category='encode',
        icon='GZ',
        actions=('compress', 'decompress'),
        placeholder='hello gzip',
        tags=('gzip',),
    ),
    Tool(
        slug='base58',
        name='Base58 编解码',
        description='Bitcoin 风格 Base58 编解码。',
        category='encode',
        icon='58',
        actions=('encode', 'decode'),
        placeholder='Hello StackBox',
        tags=('base58',),
    ),

    # Convert
    Tool(
        slug='timestamp',
        name='Unix 时间戳',
        description='时间戳与可读时间互转，支持秒/毫秒。',
        category='convert',
        icon='⏱',
        actions=('now', 'to_datetime', 'to_timestamp'),
        placeholder='1710000000',
        options=(
            {
                'key': 'unit',
                'label': '单位',
                'type': 'select',
                'default': 'auto',
                'choices': [('auto', '自动'), ('s', '秒'), ('ms', '毫秒')],
            },
        ),
        tags=('时间戳', 'unix'),
    ),
    Tool(
        slug='number-base',
        name='进制转换',
        description='二进制 / 八进制 / 十进制 / 十六进制互转。',
        category='convert',
        icon='2↔16',
        actions=('convert',),
        placeholder='255',
        options=(
            {
                'key': 'from_base',
                'label': '输入进制',
                'type': 'select',
                'default': '10',
                'choices': [('2', '2'), ('8', '8'), ('10', '10'), ('16', '16')],
            },
        ),
        tags=('进制', 'binary'),
    ),
    Tool(
        slug='color',
        name='颜色转换',
        description='HEX / RGB / HSL 颜色互转。',
        category='convert',
        icon='◎',
        actions=('convert',),
        placeholder='#0F766E',
        tags=('color', 'hex', 'rgb'),
    ),
    Tool(
        slug='case',
        name='命名风格转换',
        description='camelCase / snake_case / kebab-case / PascalCase 等互转。',
        category='convert',
        icon='Aa',
        actions=(
            'snake', 'camel', 'pascal', 'kebab', 'constant', 'title', 'upper', 'lower',
        ),
        placeholder='helloWorldExample',
        tags=('命名', 'case'),
    ),
    Tool(
        slug='bytes-size',
        name='字节单位换算',
        description='B / KB / MB / GB / TB 换算。',
        category='convert',
        icon='B',
        actions=('convert',),
        placeholder='1048576',
        options=(
            {
                'key': 'unit',
                'label': '输入单位',
                'type': 'select',
                'default': 'B',
                'choices': [('B', 'B'), ('KB', 'KB'), ('MB', 'MB'), ('GB', 'GB'), ('TB', 'TB')],
            },
        ),
        tags=('字节', 'size'),
    ),
    Tool(
        slug='cron',
        name='Cron 表达式解析',
        description='解析 Cron 表达式并给出接下来的运行时间。',
        category='convert',
        icon='CR',
        actions=('parse',),
        placeholder='*/5 * * * *',
        tags=('cron', '定时'),
    ),
    Tool(
        slug='roman',
        name='罗马数字转换',
        description='阿拉伯数字与罗马数字互转（1-3999）。',
        category='convert',
        icon='XIV',
        actions=('to_roman', 'to_int'),
        placeholder='2026',
        tags=('roman', '罗马'),
    ),
    Tool(
        slug='chmod',
        name='chmod 权限计算',
        description='Unix 权限八进制与符号表示互转。',
        category='convert',
        icon='755',
        actions=('convert',),
        placeholder='755',
        tags=('chmod', '权限'),
    ),
    Tool(
        slug='docker-compose',
        name='docker run → Compose',
        description='把 docker run 命令转成 docker-compose 片段。',
        category='convert',
        icon='DK',
        actions=('convert',),
        placeholder='docker run -d --name web -p 8080:80 -e APP_ENV=prod nginx:alpine',
        tags=('docker', 'compose'),
    ),
    Tool(
        slug='curl-python',
        name='cURL → Python',
        description='把 cURL 命令转成 requests 代码。',
        category='convert',
        icon='cURL',
        actions=('convert',),
        placeholder='curl -X POST https://httpbin.org/post -H "Content-Type: application/json" -d \'{"ok":true}\'',
        tags=('curl', 'python'),
    ),

    # Text / Code
    Tool(
        slug='regex',
        name='正则测试',
        description='测试正则表达式匹配、分组与替换。',
        category='text',
        icon='.*',
        actions=('match', 'findall', 'replace'),
        dual_input=True,
        dual_labels=('正则表达式', '测试文本'),
        placeholder=r'(\w+)@(\w+\.\w+)',
        placeholder_b='contact ada@example.com or grace@lab.org',
        options=(
            {'key': 'flags', 'label': '标志 (i/m/s/x)', 'default': 'i', 'type': 'text'},
            {'key': 'repl', 'label': '替换为', 'default': '[$1]', 'type': 'text'},
        ),
        tags=('regex', '正则'),
    ),
    Tool(
        slug='sql-format',
        name='SQL 格式化',
        description='美化 / 压缩 SQL 语句。',
        category='text',
        icon='SQL',
        actions=('format', 'minify'),
        placeholder='select id,name from users where active=1 order by id desc',
        tags=('sql',),
    ),
    Tool(
        slug='markdown',
        name='Markdown 预览',
        description='将 Markdown 渲染为 HTML 预览。',
        category='text',
        icon='MD',
        actions=('render',),
        placeholder='# Hello\n\n- item 1\n- **bold**\n\n`code`',
        tags=('markdown',),
    ),
    Tool(
        slug='text-stats',
        name='字数统计',
        description='统计字符、单词、行数、字节与中文字数。',
        category='text',
        icon='∑',
        actions=('stats',),
        placeholder='在这里粘贴文本……',
        tags=('统计', '字数'),
    ),
    Tool(
        slug='escape',
        name='转义 / 反转义',
        description='JSON / Python / C 风格字符串转义。',
        category='text',
        icon='\\',
        actions=('json_escape', 'json_unescape', 'python_escape', 'python_unescape'),
        placeholder='line1\nline2\t"quoted"',
        tags=('escape', '转义'),
    ),
    Tool(
        slug='line-tools',
        name='行处理工具',
        description='去重、排序、去空行、加序号、反转行序。',
        category='text',
        icon='≡',
        actions=('unique', 'sort', 'sort_desc', 'trim_empty', 'number', 'reverse'),
        placeholder='banana\napple\napple\ncherry\n',
        tags=('行', '去重', '排序'),
    ),
    Tool(
        slug='css-js-minify',
        name='CSS / JS 压缩',
        description='简易压缩 CSS 与 JavaScript（去注释与空白）。',
        category='text',
        icon='{}',
        actions=('css', 'js'),
        placeholder='/* comment */\n.box {\n  color: #0f766e;\n  margin: 0;\n}',
        tags=('minify', 'css', 'js'),
    ),
    Tool(
        slug='slugify',
        name='Slugify / 路径化',
        description='把标题转成 URL 友好 slug（支持中文转拼音近似：保留可读片段）。',
        category='text',
        icon='/',
        actions=('slugify', 'filename'),
        placeholder='Hello StackBox 开发者工具',
        tags=('slug', 'url'),
    ),
    Tool(
        slug='html-format',
        name='HTML 格式化',
        description='简易美化或压缩 HTML。',
        category='text',
        icon='<>',
        actions=('format', 'minify'),
        placeholder='<div><p>Hello</p><span>StackBox</span></div>',
        tags=('html',),
    ),
    Tool(
        slug='markdown-html',
        name='Markdown ↔ HTML',
        description='Markdown 转 HTML，或剥离 HTML 标签。',
        category='text',
        icon='MD',
        actions=('md_to_html', 'strip_html'),
        placeholder='# Title\n\nHello **world**',
        tags=('markdown', 'html'),
    ),
    Tool(
        slug='env-format',
        name='.env 格式化',
        description='整理 .env 文件，或转为 JSON。',
        category='text',
        icon='ENV',
        actions=('format', 'to_json'),
        placeholder='APP_NAME=StackBox\nDEBUG = true\nNOTE=hello world',
        tags=('env', 'dotenv'),
    ),

    # Generate
    Tool(
        slug='uuid',
        name='UUID 生成',
        description='批量生成 UUID v4。',
        category='generate',
        icon='ID',
        actions=('generate',),
        placeholder='数量（默认 5）',
        options=(
            {'key': 'count', 'label': '数量', 'default': '5', 'type': 'text'},
            {
                'key': 'upper',
                'label': '大写',
                'type': 'select',
                'default': '0',
                'choices': [('0', '否'), ('1', '是')],
            },
        ),
        tags=('uuid', 'guid'),
    ),
    Tool(
        slug='uuid-v5',
        name='UUID v5',
        description='基于命名空间与名称生成确定性 UUID v5。',
        category='generate',
        icon='v5',
        actions=('generate',),
        placeholder='https://stackbox.local/tool',
        options=(
            {
                'key': 'namespace',
                'label': '命名空间',
                'type': 'select',
                'default': 'url',
                'choices': [('url', 'URL'), ('dns', 'DNS'), ('oid', 'OID'), ('x500', 'X500')],
            },
        ),
        tags=('uuid', 'v5'),
    ),
    Tool(
        slug='password-strength',
        name='密码强度检测',
        description='评估密码长度与字符种类强度。',
        category='generate',
        icon='PW',
        actions=('check',),
        placeholder='S3cure!Pass',
        tags=('password', 'strength'),
    ),
    Tool(
        slug='password',
        name='密码生成',
        description='生成高强度随机密码。',
        category='generate',
        icon='*',
        actions=('generate',),
        placeholder='长度（默认 16）',
        options=(
            {'key': 'length', 'label': '长度', 'default': '16', 'type': 'text'},
            {
                'key': 'symbols',
                'label': '含符号',
                'type': 'select',
                'default': '1',
                'choices': [('1', '是'), ('0', '否')],
            },
            {'key': 'count', 'label': '数量', 'default': '5', 'type': 'text'},
        ),
        tags=('password', '随机'),
    ),
    Tool(
        slug='lorem',
        name='Lorem Ipsum',
        description='生成占位假文。',
        category='generate',
        icon='L',
        actions=('paragraphs', 'sentences', 'words'),
        placeholder='段落数（默认 3）',
        options=(
            {'key': 'count', 'label': '数量', 'default': '3', 'type': 'text'},
        ),
        tags=('lorem', '假文'),
    ),
    Tool(
        slug='qrcode',
        name='二维码生成',
        description='将文本生成 PNG 二维码（Base64 展示）。',
        category='generate',
        icon='▣',
        actions=('generate',),
        placeholder='https://example.com',
        tags=('qr', '二维码'),
    ),
    Tool(
        slug='random',
        name='随机数 / 字符串',
        description='生成随机整数、十六进制串、Token。',
        category='generate',
        icon='?',
        actions=('int', 'hex', 'token'),
        placeholder='1-100',
        options=(
            {'key': 'count', 'label': '数量', 'default': '5', 'type': 'text'},
        ),
        tags=('random', 'token'),
    ),
    Tool(
        slug='hashids-like',
        name='短 ID 生成',
        description='基于数字生成可读短码（可逆演示）。',
        category='generate',
        icon='ID',
        actions=('encode', 'decode'),
        placeholder='123456',
        tags=('短链', 'id'),
    ),
    Tool(
        slug='nanoid',
        name='NanoID 生成',
        description='生成 URL 安全的短随机 ID。',
        category='generate',
        icon='nano',
        actions=('generate',),
        placeholder='21',
        options=(
            {'key': 'length', 'label': '长度', 'default': '21', 'type': 'text'},
            {'key': 'count', 'label': '数量', 'default': '5', 'type': 'text'},
        ),
        tags=('nanoid', 'id'),
    ),
    Tool(
        slug='ulid',
        name='ULID 生成',
        description='生成可排序的 ULID（时间戳 + 随机）。',
        category='generate',
        icon='ULID',
        actions=('generate',),
        placeholder='',
        options=(
            {'key': 'count', 'label': '数量', 'default': '5', 'type': 'text'},
        ),
        tags=('ulid', 'id'),
    ),
    Tool(
        slug='ssh-keygen',
        name='SSH 密钥生成',
        description='生成 Ed25519 / RSA OpenSSH 密钥对。',
        category='generate',
        icon='SSH',
        actions=('generate',),
        placeholder='stackbox@local',
        options=(
            {
                'key': 'algo',
                'label': '算法',
                'type': 'select',
                'default': 'ed25519',
                'choices': [('ed25519', 'Ed25519'), ('rsa', 'RSA 2048')],
            },
        ),
        tags=('ssh', '密钥'),
    ),
    Tool(
        slug='fake-data',
        name='假数据生成',
        description='生成用户 / 邮箱 / 姓名等测试数据。',
        category='generate',
        icon='FX',
        actions=('users', 'emails', 'names'),
        placeholder='数量（默认 5）',
        options=(
            {'key': 'count', 'label': '数量', 'default': '5', 'type': 'text'},
        ),
        tags=('faker', '测试数据'),
    ),
    Tool(
        slug='totp',
        name='TOTP / 动态口令',
        description='基于密钥生成 TOTP 验证码与 otpauth URI。',
        category='generate',
        icon='OTP',
        actions=('now', 'uri', 'random_secret'),
        placeholder='JBSWY3DPEHPK3PXP',
        options=(
            {'key': 'name', 'label': '账户名', 'default': 'user@stackbox', 'type': 'text'},
            {'key': 'issuer', 'label': '签发方', 'default': 'StackBox', 'type': 'text'},
        ),
        tags=('totp', '2fa'),
    ),
    Tool(
        slug='basic-auth',
        name='Basic Auth 生成',
        description='生成 / 解码 HTTP Basic Authorization 头。',
        category='generate',
        icon='BA',
        actions=('encode', 'decode'),
        placeholder='user:password',
        options=(
            {'key': 'user', 'label': '用户名（可选）', 'default': '', 'type': 'text'},
        ),
        tags=('basic', 'auth'),
    ),

    # Network
    Tool(
        slug='ip-cidr',
        name='IP / CIDR 计算',
        description='解析 IPv4 地址与 CIDR 网段信息。',
        category='network',
        icon='IP',
        actions=('parse',),
        placeholder='192.168.1.10/24',
        tags=('ip', 'cidr', '子网'),
    ),
    Tool(
        slug='user-agent',
        name='User-Agent 解析',
        description='粗解析常见 UA 字符串中的浏览器与系统信息。',
        category='network',
        icon='UA',
        actions=('parse',),
        placeholder='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
        tags=('ua', '浏览器'),
    ),
    Tool(
        slug='jwt-claims-time',
        name='JWT 时间声明',
        description='把 JWT 的 iat/exp/nbf 等时间字段可读化（粘贴完整 JWT 或 payload JSON）。',
        category='network',
        icon='⏱',
        actions=('explain',),
        placeholder='{"iat":1516239022,"exp":1710000000,"nbf":1516239022}',
        tags=('jwt', 'exp'),
    ),
    Tool(
        slug='url-parser',
        name='URL 解析',
        description='拆解 URL 的 scheme/host/path/query 等字段。',
        category='network',
        icon='URL',
        actions=('parse',),
        placeholder='https://user:pass@example.com:8443/path?q=1#hash',
        tags=('url', '解析'),
    ),
    Tool(
        slug='pem-decode',
        name='PEM 证书/密钥解析',
        description='解析 PEM 证书或公私钥的基本信息。',
        category='network',
        icon='PEM',
        actions=('decode',),
        placeholder='-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----',
        tags=('pem', '证书', 'ssl'),
    ),

    # Reference
    Tool(
        slug='http-status',
        name='HTTP 状态码',
        description='常见 HTTP 状态码速查。',
        category='reference',
        icon='HTTP',
        actions=('lookup', 'list'),
        placeholder='404',
        template='toolbox/tool_reference.html',
        tags=('http', '状态码'),
    ),
    Tool(
        slug='mime-types',
        name='MIME 类型速查',
        description='常见文件扩展名与 MIME Type 对照。',
        category='reference',
        icon='MIME',
        actions=('lookup', 'list'),
        placeholder='json',
        template='toolbox/tool_reference.html',
        tags=('mime', 'content-type'),
    ),
    Tool(
        slug='content-headers',
        name='常用 HTTP 头',
        description='开发中常见请求/响应头说明。',
        category='reference',
        icon='HDR',
        actions=('list',),
        placeholder='',
        template='toolbox/tool_reference.html',
        tags=('header',),
    ),
    Tool(
        slug='regex-cheat',
        name='正则速查表',
        description='常用正则语法速查。',
        category='reference',
        icon='.*',
        actions=('list', 'lookup'),
        placeholder='\\d',
        template='toolbox/tool_reference.html',
        tags=('regex', '速查'),
    ),
]


_TOOL_MAP = {t.slug: t for t in TOOLS}


def get_tool(slug: str) -> Tool | None:
    return _TOOL_MAP.get(slug)


def tools_by_category() -> list[tuple[str, str, list[Tool]]]:
    result = []
    for key, label in CATEGORIES:
        items = [t for t in TOOLS if t.category == key]
        if items:
            result.append((key, label, items))
    return result


def search_tools(query: str) -> list[Tool]:
    q = query.strip().lower()
    if not q:
        return list(TOOLS)
    out = []
    for t in TOOLS:
        blob = ' '.join([t.name, t.description, t.slug, *t.tags]).lower()
        if q in blob:
            out.append(t)
    return out
