#!/usr/bin/env python3
"""Turn discovery candidates into an integration checklist (and optional stubs).

Does not invent unsafe tools. Prefer implementing processors manually for quality.
This script:
- reads weekly_candidates.json / candidates.json
- prints categorized high/medium gaps still missing
- optionally opens a GitHub issue as a weekly integrate reminder
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.request
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'stackbox.settings')

import django

django.setup()

from toolbox.discovery import lib as disco  # noqa: E402
from toolbox.registry import TOOLS  # noqa: E402


def load_gaps() -> list[dict]:
    weekly = disco.load_json(disco.WEEKLY_PATH, {})
    nightly = disco.load_json(disco.CANDIDATES_PATH, {})
    gaps = weekly.get('gaps') or nightly.get('gaps') or []
    have = {t.slug for t in TOOLS}
    return [g for g in gaps if g.get('slug_hint') not in have]


def create_issue(gaps: list[dict]) -> None:
    token = os.environ.get('GITHUB_TOKEN') or os.environ.get('GH_TOKEN')
    repo = os.environ.get('GITHUB_REPOSITORY')
    if not token or not repo:
        print('No GITHUB_TOKEN/REPO; printing checklist only')
        return
    high = [g for g in gaps if g.get('priority') == 'high']
    medium = [g for g in gaps if g.get('priority') == 'medium']
    lines = [
        '每周集成提醒：根据全网扫描结果，优先补齐下列工具。',
        '',
        f'当前已集成：{len(TOOLS)} · 待办：{len(gaps)}',
        '',
        '### High',
        '',
    ]
    for g in high[:30]:
        lines.append(f"- [ ] `{g.get('slug_hint')}` — {g.get('name')} ({g.get('category')}/{g.get('region', 'intl')})")
    lines += ['', '### Medium', '']
    for g in medium[:40]:
        lines.append(f"- [ ] `{g.get('slug_hint')}` — {g.get('name')} ({g.get('category')})")
    lines += [
        '',
        '约束：Django / 无数据库 / 无付费 API；优先纯 Python 可实现工具。',
        '',
        '_Generated by `scripts/integrate_candidates.py`_',
    ]
    payload = json.dumps(
        {
            'title': f'Weekly integrate checklist ({datetime.now().date().isoformat()}) — {len(gaps)} tools',
            'body': '\n'.join(lines),
            'labels': ['tool-scan', 'integrate', 'enhancement'],
        }
    ).encode('utf-8')
    req = urllib.request.Request(
        f'https://api.github.com/repos/{repo}/issues',
        data=payload,
        method='POST',
        headers={
            'Accept': 'application/vnd.github+json',
            'Authorization': f'Bearer {token}',
            'User-Agent': 'StackBox-Integrate',
            'Content-Type': 'application/json',
        },
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.loads(resp.read().decode('utf-8'))
        print('Issue:', data.get('html_url'))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--create-issue', action='store_true')
    args = parser.parse_args()
    gaps = load_gaps()
    print(f'Installed={len(TOOLS)} pending={len(gaps)}')
    for g in gaps[:30]:
        print(f"  [{g.get('priority')}] {g.get('category')}/{g.get('slug_hint')} — {g.get('name')}")
    if args.create_issue:
        if gaps:
            create_issue(gaps)
        else:
            print('No gaps; skip issue')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
